require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Steepfile'

Gemspec/DevelopmentDependencies:
  AllowedGems:
    - numo-linalg
    - numo-tiny_linalg

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  AllowedPatterns: ['(\A|\s)#']

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 8
  MaxOptionalParameters: 4

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

RSpec/ExampleLength:
  Max: 16

RSpec/FilePath:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 16

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  Enabled: false

Security/MarshalLoad:
  Exclude:
    - 'spec/**/*'
